name: Flutter CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '11.x'
      - uses: subosito/flutter-action@v2.19.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - name: Build Web
        run: flutter build web
      - name: GitHub Pages action
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'build/web'
          user_name: 'Bervianto Leo Pratama'
          user_email: 'bervianto.leo@gmail.com'
